
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author muhro
 */
public class absen extends javax.swing.JFrame {

    /**
     * Creates new form absen
     */
    public absen() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ignore){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        absensi = new javax.swing.JButton();
        rekap_mingguan = new javax.swing.JButton();
        rekap_bulanan = new javax.swing.JButton();
        performa = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 249));

        absensi.setBackground(new java.awt.Color(248, 249, 249));
        absensi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        absensi.setForeground(new java.awt.Color(53, 96, 97));
        absensi.setText("Absensi");
        absensi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 96, 97), 3));
        absensi.setContentAreaFilled(false);
        absensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        absensi.setFocusPainted(false);
        absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensiActionPerformed(evt);
            }
        });

        rekap_mingguan.setBackground(new java.awt.Color(248, 249, 249));
        rekap_mingguan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rekap_mingguan.setForeground(new java.awt.Color(53, 96, 97));
        rekap_mingguan.setText("Rekap Mingguan");
        rekap_mingguan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 96, 97), 3));
        rekap_mingguan.setContentAreaFilled(false);
        rekap_mingguan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rekap_mingguan.setFocusPainted(false);
        rekap_mingguan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekap_mingguanActionPerformed(evt);
            }
        });

        rekap_bulanan.setBackground(new java.awt.Color(248, 249, 249));
        rekap_bulanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rekap_bulanan.setForeground(new java.awt.Color(53, 96, 97));
        rekap_bulanan.setText("Rekap Bulanan");
        rekap_bulanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 96, 97), 3));
        rekap_bulanan.setContentAreaFilled(false);
        rekap_bulanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rekap_bulanan.setFocusPainted(false);
        rekap_bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekap_bulananActionPerformed(evt);
            }
        });

        performa.setBackground(new java.awt.Color(248, 249, 249));
        performa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        performa.setForeground(new java.awt.Color(53, 96, 97));
        performa.setText("Performa siswa");
        performa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 96, 97), 3));
        performa.setContentAreaFilled(false);
        performa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        performa.setFocusPainted(false);
        performa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performaActionPerformed(evt);
            }
        });

        admin.setBackground(new java.awt.Color(248, 249, 249));
        admin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        admin.setForeground(new java.awt.Color(53, 96, 97));
        admin.setText("Admin");
        admin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 96, 97), 3, true));
        admin.setContentAreaFilled(false);
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setFocusPainted(false);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(absensi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rekap_bulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(performa, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rekap_mingguan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(absensi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rekap_bulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(rekap_mingguan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jPanel2.setBackground(new java.awt.Color(71, 110, 110));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        absensi a = new absensi();
        a.setVisible(true);
    }//GEN-LAST:event_absensiActionPerformed

    private void rekap_mingguanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekap_mingguanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        rekapminggu rm = new rekapminggu();
        rm.setVisible(true);
    }//GEN-LAST:event_rekap_mingguanActionPerformed

    private void rekap_bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekap_bulananActionPerformed
        // TODO add your handling code here:
        this.dispose();
        rekapbulan rb = new rekapbulan();
        rb.setVisible(true);
    }//GEN-LAST:event_rekap_bulananActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        this.dispose();
        admin a = new admin();
        a.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda Berhasil Log out, silahkan login kembali !");
        this.dispose();
        login login = new login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void performaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        performasiswa ps = new performasiswa();
        ps.setVisible(true);
    }//GEN-LAST:event_performaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new absen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absensi;
    private javax.swing.JButton admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton performa;
    private javax.swing.JButton rekap_bulanan;
    private javax.swing.JButton rekap_mingguan;
    // End of variables declaration//GEN-END:variables
}
