
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author muhro
 */
public class admin extends javax.swing.JFrame {

    private int foundID = -1;
    private final Connection conn;

    public admin() {
        initComponents();
        conn = koneksi.getKoneksi();
        show_data(tabel); // Memanggil show_data untuk pertama kali saat form dibuka
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        no_absen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        icon_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        no_absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_absenActionPerformed(evt);
            }
        });

        jLabel2.setText("No Absen");

        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });

        jLabel3.setText("Kelas");

        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        jenis_kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_kelaminActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Kelamin");

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        icon_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_search.png"))); // NOI18N
        icon_search.setPreferredSize(new java.awt.Dimension(32, 32));
        icon_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_searchMouseExited(evt);
            }
        });
        icon_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icon_searchActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "No Absen", "Kelas", "Jenis Kelamin"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama)
                            .addComponent(search)
                            .addComponent(jLabel2)
                            .addComponent(no_absen)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jenis_kelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ubah)
                                    .addComponent(tambah)
                                    .addComponent(hapus)
                                    .addComponent(reset)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(icon_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(no_absen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenis_kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis_kelaminActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void no_absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_absenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_absenActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String nameToSearch = search.getText();
        if (!nameToSearch.isEmpty()) {
            try {
                String sql = "SELECT * FROM siswa WHERE nama = ?";
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setString(1, nameToSearch);
                ResultSet rs = stm.executeQuery();
                if (rs.next()) {
                    nama.setText(rs.getString("nama"));
                    no_absen.setText(rs.getString("no_absen"));
                    kelas.setText(rs.getString("kelas"));
                    jenis_kelamin.setSelectedItem(rs.getString("jenis_kelamin"));
                    foundID = rs.getInt("id");
                    JOptionPane.showMessageDialog(null, "Data " + nameToSearch + " ditemukan");
                } else {
                    JOptionPane.showMessageDialog(null, "Data " + nameToSearch + " tidak ditemukan");
                    foundID = -1;
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silakan masukkan nama yang ingin dicari");
        }
        search.requestFocus();
    }//GEN-LAST:event_searchActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO siswa (nama, no_absen, kelas, jenis_kelamin) VALUES (?, ?, ?, ?)";
            PreparedStatement stmnt = conn.prepareStatement(sql);
            stmnt.setString(1, nama.getText());
            stmnt.setString(2, no_absen.getText());
            stmnt.setString(3, kelas.getText());
            stmnt.setString(4, jenis_kelamin.getSelectedItem().toString());

            stmnt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
            show_data(tabel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Disimpan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tambahActionPerformed

    
    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        if (foundID != -1) {
            try {
                String sql = "UPDATE siswa SET nama = ?, no_absen = ?, kelas = ?, jenis_kelamin = ? WHERE id = ?";
                PreparedStatement stmnt = conn.prepareStatement(sql);
                stmnt.setString(1, nama.getText());
                stmnt.setString(2, no_absen.getText());
                stmnt.setString(3, kelas.getText());
                stmnt.setString(4, jenis_kelamin.getSelectedItem().toString());
                stmnt.setInt(5, foundID);

                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                show_data(tabel);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang ditemukan untuk diubah");
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    if (foundID != -1) {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    String sql = "DELETE FROM siswa WHERE id = ?";
                    PreparedStatement stmnt = conn.prepareStatement(sql);
                    stmnt.setInt(1, foundID);
                    stmnt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    show_data(tabel);

                    foundID = -1;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Dihapus: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang ditemukan untuk dihapus");
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void icon_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icon_searchActionPerformed
        // TODO add your handling code here:
        searchActionPerformed(evt);
    }//GEN-LAST:event_icon_searchActionPerformed

    private void icon_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_searchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_searchMouseEntered

    private void icon_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_searchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_searchMouseExited

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        search.setText("");
        nama.setText("");
        no_absen.setText("");
        kelas.setText("");
        jenis_kelamin.setSelectedIndex(0);
        foundID = -1;
    }//GEN-LAST:event_resetActionPerformed

        public void show_data(JTable jTable) {
        DefaultTableModel tabelModel = new DefaultTableModel();
        tabelModel.addColumn("Nama");
        tabelModel.addColumn("No Absen");
        tabelModel.addColumn("Kelas");
        tabelModel.addColumn("Jenis Kelamin");

        try {
            String sql = "SELECT * FROM siswa";
            PreparedStatement stmnt = conn.prepareStatement(sql);
            ResultSet rs = stmnt.executeQuery();

            while (rs.next()) {
                tabelModel.addRow(new Object[]{
                    rs.getString("nama"),
                    rs.getString("no_absen"),
                    rs.getString("kelas"),
                    rs.getString("jenis_kelamin")
                });
            }
            jTable.setModel(tabelModel);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JButton icon_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no_absen;
    private javax.swing.JButton reset;
    private javax.swing.JTextField search;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
